name: Lastream
options:
  bundleIdPrefix: com.lastapple
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""

packages:
  SignalRClient:
    url: https://github.com/moozzyk/SignalR-Client-Swift
    from: "0.9.0"

targets:
  Lastream:
    type: application
    platform: iOS
    sources:
      - path: Lastream
        excludes:
          - "**/*.entitlements"
    settings:
      base:
        INFOPLIST_FILE: Lastream/Info.plist
        CODE_SIGN_ENTITLEMENTS: Lastream/Lastream.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.lastapple.lastapple
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleDisplayName: Lastream
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.music"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
    dependencies:
      - package: SignalRClient
    entitlements:
      path: Lastream/Lastream.entitlements

  LastreamTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LastreamTests
    dependencies:
      - target: Lastream
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lastapple.lastapple.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Lastream.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Lastream"
        BUNDLE_LOADER: "$(TEST_HOST)"

  LastreamUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LastreamUITests
    dependencies:
      - target: Lastream
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lastapple.lastapple.uitests
        TEST_TARGET_NAME: Lastream

schemes:
  Lastream:
    build:
      targets:
        Lastream: all
        LastreamTests: [test]
        LastreamUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: LastreamTests
          parallelizable: true
          randomExecutionOrder: true
        - name: LastreamUITests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
